"""add panel to MQTTControl

Revision ID: 81c3a41a9ada
Revises: 9ffd1db96490
Create Date: 2017-04-08 18:25:26.903681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c3a41a9ada'
down_revision = '9ffd1db96490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mqtt_controls', sa.Column('panel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mqtt_controls', 'panels', ['panel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mqtt_controls', type_='foreignkey')
    op.drop_column('mqtt_controls', 'panel_id')
    # ### end Alembic commands ###
