"""add update time

Revision ID: f4c55277bc6f
Revises: f5d707713ae0
Create Date: 2017-04-02 14:22:31.534188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c55277bc6f'
down_revision = 'f5d707713ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mqtt_items', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mqtt_items', 'update_time')
    # ### end Alembic commands ###
